Ext.define("core.mvc_test.store.Store",{
	extend:'Ext.data.Store',
	model:'core.mvc_test.model.Model',
	autoLoad:false,
	proxy:{
		type:'ajax',
		url:'/web/test/testdata!getResult.action',
		//type:'memory',
		reader:{
			type:'json',
			root:'data'
		}
	}
});