Ext.define("core.mes.model.reportforms.wx.ModelMo",{
	extend:'Ext.data.Model',
	fields:[
		{name:'MOId'},  
		{name:'MOName'},		
		{name:'MakeUpCount'},	
		{name:'productName'},
		{name:'ProductDescription'}
	]
});