Ext.define("core.mes.model.reportforms.wx.Model",{
	extend:'Ext.data.Model',
	fields:[
		{name:'在线维修时间'},  
		{name:'LotSN'},
		{name:'MOName'},
		{name:'ProductDescription'},
		{name:'ProductSpecification'},
		{name:'当前所在工站'},
		{name:'UserCodeDescription'},
		{name:'RepairComment'},
		{name:'UserCodeDescription'},
		{name:'repairUser'}
	]
});