Ext.define("core.mes.model.reportforms.gdwlblmx.Model",{
	extend:'Ext.data.Model',
	fields:[
		{name:'MOId'},  
		{name:'ProductId'},
		{name:'ProductName'},
		{name:'ItemQtyRequired'},
		{name:'备料数量'},
		{name:'ProductDescription'},
		{name:'ProductSpecification'}	
	]
});