Ext.define("core.mes.model.reportforms.dip_wx.Model",{
	extend:'Ext.data.Model',
	fields:[
		{name:'维修入库时间'},  
		{name:'维修时间'},
		{name:'维修出库时间'},
		{name:'VendorLotSN'},
		{name:'MOName'},
		{name:'ProductDescription'},
		{name:'ProductSpecification'},
		{name:'当前所在工站'},
		{name:'故障代码'},
		{name:'UserCodeDescription'},
		{name:'RepairComment'},
		{name:'UserCodeDescription'},
		{name:'repairUser'}
	]
});