Ext.define("core.silou_line_kanban.model.Model",{
	extend:'Ext.data.Model',
	fields:[
		{name:'fDate'},
		{name:'WorkcenterName'},
		{name:'ProductDescription'},
		{name:'SpecificationName'},
		{name:'StandardProductivity'},
		{name:'1',type:'int'},
		{name:'2',type:'int'},
		{name:'3',type:'int'},
		{name:'4',type:'int'},
		{name:'5',type:'int'},
		{name:'6',type:'int'},
		{name:'7',type:'int'},
		{name:'8',type:'int'},
		{name:'9',type:'int'},
		{name:'10',type:'int'},
		{name:'11',type:'int'},
		{name:'12',type:'int'},
		{name:'累计'}
	]	
});