Ext.define("core.course_manage.view.SearchUserSkill",{
	extend:'Ext.Panel',
	alias:'widget.coursemanage_searchuserskill',
	layout:'border',
	items:[
		{
			xtype:'form',
			region:'north',
			height:150,
			bodyPadding:5,
			defaultType:'textfield',
			layout:'absolute',
			labelAlign:"right",
            defaults:{
				labelAlign:"right",
				msgTarget:'under'
			},
			items:[
				{
					fieldLabel:'工号',
					name:'workNumber',
					allowBlank:false,
					x:180,
					y:30
				}
			],
			buttons:[
				{text:'提交',action:'submit'},
				{text:'重置',action:'reset'}
			]
		},
		{
			xtype:'gridpanel',
			region:'center',
			columns:[
				{xtype:'rownumberer',text:'序号',width:50},
				{dataIndex:'UserNumber',text:'工号',width:100},
				{dataIndex:'UserName',text:'姓名',width:100},
				{dataIndex:'UserDuty',text:'职称',width:100},
				{dataIndex:'SkillName',text:'技能名称',width:150},
				{dataIndex:'SkillCategory',text:'技能类别',width:150},
				{dataIndex:'SkillRemark',text:'备注',wdith:150}
			],
			store:'core.course_manage.store.UserSkillStore'
		}
	]
	
});