 /***************************************************************************
  								<收料查询操作界面> 
 ***************************************************************************/
 
  Ext.define("core.xigao.view.main.content.xghsyffsm.Operate",{
  	extend:"core.xigao.base.XiGaoBaseForm",
 	alias:'widget.xghsyffsm_operate',
	items:[
			{
			xtype:'label',
			text:'锡膏条码SN:',
			x:20,
			y:15
		},
		{
			xtype:'textfield',
			allowBlank:false,
			name:'sn',
			x:20,
			y:35
		},
		{
			xtype:'label',
			text:'编码代码:',
			x:200,
			y:15
		},
		{
			xtype:'textfield',
			name:'number_code',
			x:200,
			y:35
		},
		{
			xtype:'label',
			text:'锡膏名:',
			x:380,
			y:15
		},
		{
			xtype:'textfield',
			name:'name',
			x:380,
			y:35
		},
//////////////////////////////////////////////////////////				
		{
			xtype:'label',
			text:'锡膏型号:',
			x:20,
			y:75
		},
		{
			xtype:'textfield',
			name:'type',
			x:20,
			y:95
		},
		{
			xtype:'label',
			text:'锡膏入库时间:',
			x:200,
			y:75
		},
		{
			xtype:'textfield',
			name:'in_time',
			x:200,
			y:95
		},
		{
			xtype:'label',
			text:'SMT线别:',
			x:380,
			y:75
		},
		{
			xtype:'textfield',
			name:'line',
			x:380,
			y:95
		},
		
////////////////////////////////////////////////////////////	
		{
			xtype:'label',
			text:'进厂日期:',
			x:20,
			y:145
		},
		{
			xtype:'textfield',
			name:'in_date',
			x:20,
			y:165
		},
		{
			xtype:'label',
			text:'有效日期:',
			x:200,
			y:145
		},
		{
			xtype:'textfield',
			name:'effective_date',
			x:200,
			y:165
		}
	],
	buttons:[{text:'锡膏回收扫描',action:'scan1'},{text:'锡膏发放扫描',action:'scan2'}]
 });