Ext.define("core.sop.model.MOName_SMT_ViewList_Model",{
	extend:'Ext.data.Model',
	fields:[
		{name:'rowNum'}, 
		{name:'MOId'},
		{name:'MOName'},
		{name:'productName'},
		{name:'ProductDescription'}
	]
});