Ext.define("core.mes.model.reportforms.wlsldhc.Model",{
	extend:'Ext.data.Model',
	fields:[
		{name:'POName'},  
		{name:'MDocCode'},
		{name:'LotQty'},
		{name:'ProductID'},
		{name:'ProductName'},
		{name:'ProductDescription'},
		{name:'IsmDoc'}
	]
});