 /***************************************************************************
  								<收料查询操作界面> 
 ***************************************************************************/

  Ext.define("core.xigao.view.main.content.xgcbxsm.Operate",{
  	extend:"core.xigao.base.XiGaoBaseForm",
 	alias:'widget.xgcbxsm_operate',
	items:[
		{
			xtype:'label',
			text:'锡膏条码SN:',
			x:20,
			y:15
		},
		{
			xtype:'textfield',
			allowBlank:false,
			name:'sn',
			x:20,
			y:35
		},
		{
			xtype:'label',
			text:'编码代码:',
			x:200,
			y:15
		},
		{
			xtype:'textfield',
			name:'number_code',
			x:200,
			y:35
		},
		{
			xtype:'label',
			text:'锡膏名:',
			x:380,
			y:15
		},
		{
			xtype:'textfield',
			name:'name',
			x:380,
			y:35
		},
//////////////////////////////////////////////////////////				
		{
			xtype:'label',
			text:'锡膏型号:',
			x:20,
			y:85
		},
		{
			xtype:'textfield',
			name:'type',
			x:20,
			y:105
		},
		{
			xtype:'label',
			text:'锡膏入库时间:',
			x:200,
			y:85
		},
		{
			xtype:'textfield',
			name:'in_time',
			x:200,
			y:105
		},
		{
			xtype:'label',
			text:'执行人:',
			x:380,
			y:85
		},
		{
			xtype:'textfield',
			name:'executor_operator',
			x:380,
			y:105
		}
	],
	buttons:[{text:'锡膏回温扫描',action:'scan1'},{text:'锡膏出冰箱扫描',action:'scan2'}]
 });